feat: check affiliation utils
LeslieLeung/opensource-lighthouse pull request #10
Opened 2024-07-09 14:38 UTC by chesha1

check affiliation utils

repo-level affiliation check function, it can receive two types of inputs:
- a list of potiential companies, calculating the percentage of commits made by every company. It indicates the relative realtion between the companies and the sum of output is 1
- a single company, calculating the absolute percentage of commits made by the company

2024-07-10 02:08 UTC, LeslieLeung commented
Consider using the `pygithub` package in the project, which wraps the GitHub API. It can handle pagination and retry functionalities, saving you from writing the requests manually.

2024-07-10 03:48 UTC, chesha1 commented
Fixed. Please review it again

2024-07-10 18:32 UTC, LeslieLeung requested changes
The overall code looks good except for some styling issues.

BTW, have you run this code on some of the major repos? I wonder what the results are.

2024-07-10 18:32 UTC, LeslieLeung commented on utils.py
> +        contributor_company = contributor_company.replace('@', '').strip()
You can use a one-liner:
```python
contributor_company = (contributor.company or '').upper().replace('@', '').strip()
```

2024-07-11 04:20 UTC, chesha1 commented
Fixed. Please review it again.

I leave an example in `utils.py` to calculate contributions from companies in `kubernetes/kubernetes`, considering the first 100 contributors.

The result is below:

Contributions by company: {'GOOGLE': 62.47533868209917, 'MICROSOFT': 8.299355517558858, 'RED HAT': 16.085755622780482, 'DATABRICKS': 4.218729448901749, 'INTEL': 3.4328554517953442, 'AMAZON WEB SERVICES': 2.7620676048928057, 'GOLDMAN SACHS': 2.72589767197159}

Contributions by single company GOOGLE: 28.60196600882145 (this is because there is a robot with no company in the repo contributing most of the commits)

2024-07-12 01:24 UTC, LeslieLeung approved these changes

2024-07-12 02:14 UTC, LeslieLeung commented
The bot you mentioned must be the ci bot. This is kind of tricky, we can exclude merge commits or bot accounts, but there is no accurate way to do this.

And upon checking up that bot, I found some edge cases that your code might not cover.

- A person that might be affiliated to one company, but did not specified on profile
- A person once worked for company A and then moved on to B
- Used different name for one company, e.g. `Red Hat` and `Red Hat, Inc`

Also, I found an [API](https://ossinsight.io/docs/api/list-organizations-of-pr-creators) from ossinsight that can list the organizations of PR creators, you can check that out. They have a [chart](https://ossinsight.io/analyze/kubernetes/kubernetes#people) that shows the percentage of contributors from different orgs.

And they also mentioned this:

> In the overall data, about 5.62% of GitHub users has valid organization information.

2024-07-12 03:34 UTC, chesha1 commented
Finding CI robots is challenging, so I recommend using `calculate_contributions_by_company` rather than `calculate_single_company_contributions`. The results from `calculate_contributions_by_company` are guided by a list of input companies, which helps exclude potential CI bots.

Although some users do not show their companies, we can assume the distribution of such users is similar across all companies. Each company has a certain number of developers who do not show their affiliations. Thus, using `calculate_contributions_by_company` will not be affected as it shows the relative percentage of contributions from the input companies.

Handling situations where a person once worked for Company A and then moved to Company B is difficult. This is indeed a problem, and I do not have good idea about it now.

To address cases where different names are used for the same company (e.g., Red Hat and Red Hat, Inc), we can use the shortest input company name to match all variations:
```python
company = company.upper().replace('@', '').strip()

count = False
for target_company in companies:
    if company.find(target_company) != -1:
        company = target_company
        count = True
```
There already exists codes that tries to match all possible company names with the shortest input.

In the above example, input compaines is `['GOOGLE', 'MICROSOFT', 'INTEL', 'Red Hat', 'Databricks', 'Amazon Web Services', 'Goldman Sachs']`. It matches `Intel GmbH` expectedly: https://github.com/pohly

2024-07-14 20:01 UTC, LeslieLeung commented
I think I didn't make my point clear. The key here is that we may never get an accurate rate from this method, and releasing inaccurate data would be irresponsible.

An alternative could be using data from the OSSInsight API I mentioned earlier. We should clarify that we used their data and that it has not been proven to be accurate.

2024-07-15 01:34 UTC, chesha1 commented
Understood. I couldn't find a detailed introduction to this API, so I am wondering if the company of the PR creator is stored by OSS Insight each time. If so, we can assume their data is valid as it excludes the impact of resignations and new hires.

Another major advantage is that data from OSS Insight excludes CI bots and renames teams to larger company entities, like changing `Intel GmbH` to `Intel`.

Do you know if there is a Python library to access OSS Insight? It seems that I have to use `requests` to access the OSS Insight API.

2024-07-15 01:49 UTC, chesha1 commented
Another big problem is the variations of a single company name. For example, OSS Insight data may include `red hat, inc`, `red hat, inc.`, `redhatofficial`, and `red hat` as separate entities, calculating their contributions independently.

Do you have any good ideas to handle this problem? One straightforward solution is to provide a list of company names as input, remove special characters from the company names in OSS Insight, and try to match them. If a match is found, we can merge the variants into the given company name. However, this approach may have many corner cases that require manual adjustments.

2024-07-23 08:11 UTC, LeslieLeung commented
Sorry for the delay.

Do you think we can agree that:
a. It's impossible to precisely track each company's contribution
b. OSS Insight provides reasonably acceptable results

If so, we can use its data (it's fine using requests) and include a reference to it.

2024-07-24 05:26 UTC, chesha1 commented
Two new functions from the OSS Insight API:
- `list_organizations_of_pr_creators` returns the raw data.
- `is_company_dominant_in_repo` checks if a company has made a significant number of contributions to a repository. It takes a threshold as input, and if the result is false, the repo can be safely attributed to foundations.

2024-07-26 01:29 UTC, LeslieLeung approved these changes

2024-07-26 01:29 UTC, merged